version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: nextjs_auth_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextauth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 